spring:
  profiles:
    active: ${ACTIVE:dev}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

wx:
  app-id: xxx
  secret: xxx



mybatis-plus:
  mapper-locations: classpath:mapperxml/*.xml
