spring:
  profiles:
    active: ${ACTIVE:dev}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

wx:
  app-id: wxdbce1cd0903937cd
  secret: 1951b5a4bd66dfca528e9dbd77fa2f91

mybatis-plus:
  mapper-locations: classpath:mapperxml/*.xml
